services:
  mongodb:
    image: mongo:7.0
    container_name: cms-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ms-cms
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mongodb_data:/data/db

  cms-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-cms-app
    ports:
      - "8086:8086"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=ms-cms
      - MONGO_USER=admin
      - MONGO_PASSWORD=password
      - JWT_SECRET=8w9eK7sVh3FQ2mJ6lP0rXyZtN1bQ4uDkFvHsT2cW+Eo=
    restart: on-failure

volumes:
  mongodb_data: