server:
  port: 8086
  servlet:
    context-path: /api/ms.cms
spring:
  application:
    name: ms.cms
  mongodb:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${MONGO_DB:ms-cms}
    username: ${MONGO_USER:admin}
    password: ${MONGO_PASSWORD:password}
    authentication-database: admin
  data:
    mongodb:
      auto-index-creation: true
      additional-settings:
        maxConnectionIdleTime: 60000
        connectTimeout: 10000
    jackson:
      serialization:
        write-dates-as-timestamps: true
      deserialization:
        read-date-timestamps-as-nanoseconds: false

jwt:
  secret: ${JWT_SECRET:8w9eK7sVh3FQ2mJ6lP0rXyZtN1bQ4uDkFvHsT2cW+Eo=}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG